version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./myapp
    volumes:
      - /var/www/frontend:/app/dist  # ✅ 让 Vue `dist/` 直接输出到宿主机
    depends_on:
      - backend
    command: ["npm", "run", "build"]  # ✅ 运行构建后退出